worker_processes 1;

events { worker_connections 1024; }

http {
    include mime.types;
    # Configuration for the server
    sendfile on;
    server {
        listen 80;
        server_name dao.irb.hr;
        
      	location / {
          	root   /usr/share/nginx/html;
          	index  index.html;
          	add_header Access-Control-Allow-Origin *;
          	add_header Pragma "no-cache";
          	add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
          	try_files  $uri /index.html;
      }
        location /api/predict {
            # adjust port of backend to desired port
            proxy_pass http://flask:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
        location /api/explain {
            # adjust port of backend to desired port
            proxy_pass http://flask:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
         location /api/complement {
            # adjust port of backend to desired port
            proxy_pass http://flask:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
      }
}
